<?php

$labels['ai_user_info'] = 'Benutzer Information';
$labels['ai_default_identity'] = 'Standard Identität';
$labels['ai_user_id'] = 'Benutzer ID';
$labels['ai_created'] = 'Erstellt am';
$labels['ai_last_login'] = 'Letzter Login';
$labels['ai_failed_login'] = 'Fehlgeschlagener Login';
$labels['ai_username'] = 'Benutzername';
$labels['ai_password'] = 'Passwort';
$labels['ai_storage_info'] = 'Speicher Informationen';
$labels['ai_total_storage'] = 'Gesamter Speicher';
$labels['ai_used_storage'] = 'Verwendeter Speicher';
$labels['ai_free_storage'] = 'Freier Speicher';
$labels['ai_mail_setup_info'] = 'E-Mail-Account-Einstellungen';
$labels['ai_imap_server'] = 'IMAP-Servername';
$labels['ai_imap_port'] = 'IMAP-Port';
$labels['ai_imap_ssl'] = 'IMAP-Verschlüsselungsmethode';
$labels['ai_imap_prefix'] = 'IMAP-Pfad Prefix';
$labels['ai_smtp_server'] = 'SMTP-Servername';
$labels['ai_smtp_port'] = 'SMTP-Port';
$labels['ai_smtp_ssl'] = 'SMTP-Verschlüsselungsmethode';
$labels['account_info'] = 'Profil Info';
$labels['ai_download_apple_profile'] = 'Exportiere E-Mail-Provisierungs-Profil';
$labels['ai_download_ios'] = 'iPhone iOS / iPadOS / Mac OSX';
$labels['ai_payload_description'] = 'WebMail';
$labels['ai_download_profiles'] = 'Profil Download';

?>
