<?php

$labels['ai_user_info'] = 'User Info';
$labels['ai_default_identity'] = 'Default Identity';
$labels['ai_user_id'] = 'User ID';
$labels['ai_created'] = 'Created';
$labels['ai_last_login'] = 'Last Login';
$labels['ai_failed_login'] = 'Failed Login';
$labels['ai_username'] = 'Username';
$labels['ai_password'] = 'Password';
$labels['ai_storage_info'] = 'Storage Info';
$labels['ai_total_storage'] = 'Total Storage';
$labels['ai_used_storage'] = 'Used Storage';
$labels['ai_free_storage'] = 'Free Storage';
$labels['ai_mail_setup_info'] = 'Mail Setup Info';
$labels['ai_imap_server'] = 'Incoming IMAP Server';
$labels['ai_imap_port'] = 'Incoming IMAP Port';
$labels['ai_imap_ssl'] = 'IMAP Encrypted Connection';
$labels['ai_imap_prefix'] = 'IMAP Path Prefix';
$labels['ai_smtp_server'] = 'Outgoing SMTP Server';
$labels['ai_smtp_port'] = 'Outgoing SMTP Port';
$labels['ai_smtp_ssl'] = 'SMTP Encrypted Connection';
$labels['account_info'] = 'Account Info';
$labels['ai_download_apple_profile'] = 'Download Apple Profile';
$labels['ai_download_ios'] = 'iPhone iOS / iPadOS / Mac OSX';
$labels['ai_payload_description'] = 'WebMail';
$labels['ai_download_profiles'] = 'Download Profiles';

?>
